title: Claude Conversation Exporter
description: A browser extension for exporting Claude conversations
baseurl: "/Claude-Interaction-Exporter"
url: "https://strivenword.github.io"

remote_theme: mmistakes/minimal-mistakes-jekyll

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

exclude:
  - .git
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
