source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"
gem "minimal-mistakes-jekyll"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-include-cache"
gem "webrick"
gem "faraday-retry"
